# 日志等级，设置为默认即可
LogLevel: Info

# 服务器监听地址
Location: "127.0.0.1"

# 服务器端口
Port: 9200

# 鉴权Token,不需要时设置为空字符串
AccessToken: ""

# Universal请求路径
UniversalPath: ""

# 心跳包超时设置(秒)
# 此值请不要小于或等于客户端心跳包的发送间隔
HeartBeatTimeOut: 10

# 客户端API调用超时设置(毫秒)
# 默认为1000无需修改
ApiTimeOut: 2000