# 各模块的开关
ModuleSwitch:
  #抽奖功能
  Raffle: false
  #打劫
  Rob: false
  #救援
  Rescur: false
  #莲 bot启用
  LianBot: true
  #莲 启用ai对话
  IsAI: true
  #随机色图
  Hso: true
  #复读模式
  Reread: true
# 随机色图设置
HsoConfig:
  #色图源 Local/Lolicon/Yukari
  Source: Yukari
  #，如果没有设置0为null即可
  PximyProxy: null
  #是否使用本地缓存
  UseCache: false
  #是否使用XML格式发送图片（装逼大图）
  #有被风控风险谨慎启用
  #此功能只能在Go上使用
  CardImage: false
  #色图缓存文件夹的大小限制(MB)
  SizeLimit: 1024
  #Lolicon APIKEY
  LoliconApiKey: null
  #Yukari APIKEY
  YukariApiKey: null
  #R18
  R18: false

# Lian设置
ConfigModel:
  #响应名称
  NickName: 少侠
  #机器人名称
  BotName: 小莲
  #监听群组，例如[14561465,2564654563]
  GroupIds: null
  #小尾巴
  Tail: ~今天也是充满希望的一天
  #ai对话请求Url，建议默认值
  AiPath: http://127.0.0.1:8889/api/chat
  #群组图片存放位置
  GroupImgPath: null